# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fb758848a009bf14302f165ab01a6b868c8dcf85e33ec05fb28e8a7ab635842df36ed25d42f1803265c4564d11344b0fa8315969b0de64a0bcf22dd29e09c19

test:
  secret_key_base: eafeb0b616d117ada74950e7a57077af77e620c59c2b5699be947728911b7302203358d62e5c3cca8640eca6fbb8f63d5bbf06651e2086d4e4f0b39d7e3cfc20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

